<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>XLinkSharp</RootNamespace>
    <AssemblyName>XLinkSharp</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>Aiden A</Authors>
    <Description>Reader and writer for xlink2 ELink/SLink resource databases (XLNK) from BotW and TotK.</Description>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

</Project>
